name: mobx_widget
description: ObserverFuture, ObserverStream and ObserverText Widget - A simple way to consume MobX Observables through widgets. You can find a sort of widgets.
version: 0.4.0
author: Emanuel Braz (fastencoding@gmail.com)
homepage: https://github.com/emanuel-braz/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.0.1
  flutter_mobx: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.0.1
  build_runner: ^1.0.0

flutter:
